### ISSUE TITLE
Several applications remaining

### ISSUE THREAD

**Issue by Nothing4You** [Sycnex/Windows10Debloater#3]
Hey there,
I was just trying to test this script on a fresh windows 10 VM:
```
Windows 10 Professional
Version 1709 Build 16299.19
```
Log of latest run: [debloater-log2.txt](https://github.com/Sycnex/Windows10Debloater/files/1410437/debloater-log2.txt)

![screen shot 2017-10-24 at 12 35 09](https://user-images.githubusercontent.com/3694534/31938687-7f56fb92-b8b8-11e7-8384-fee217e1c9c4.png)

**Comment by Sycnex** [comment]
Interesting...I haven't experienced that with my Windows 10 testing VMs or any other machines in my organization.

Have you rebooted? Did you also run the script as an administrator?

**Comment by Nothing4You** [comment]
Yes, I've run the script as admin. I've run it like 5 times with multiple reboots.

**Comment by Sycnex** [comment]
I am looking into this. I've ran it on a couple of other brand new VMs in my environment and haven't experienced the issue that you're having. I am really wondering if it is due to where you're located (region based apps). 

I will update once I find a fix.

**Comment by Nothing4You** [comment]
If there's anything I can do to help you debugging please let me know.
It might also be a good idea to generate some kind of logfile (unless that already happens and I missed that)

**Comment by Sycnex** [comment]
Any help would be greatly appreciated!

For the remaining applications that aren't removed - can you take a look in HKEY_CLASSES_ROOT:\Extensions\ContractId\ and look in the sub folders and see if you can find anything that references the remaining applications?

And great idea, I will do that, thanks for the suggestion!

**Comment by Vikingat-RAGE** [comment]
I've had the exact same issue. It's live tiles. They aren't applications just links to the windows store to download them.

**Comment by Sycnex** [comment]
I believe that Vikingat-RAGE is correct - they're live tiles.

I just added code to create a registry property to disable live tiles. Go ahead and give it a shot. It is underneath the Function Protect-Privacy. When prompted to disable Cortana from being included in the index search and etc., type 'Yes' and hit enter, and it will add that property along with the other registry changes.

However, the live tiles might be cached but no other live tiles should appear.

And again, if you can, please tell me if you see those applications referenced in any of the subfolders in the registry location HKEY_CLASSES_ROOT:\Extensions\ContractId\

**Comment by Nothing4You** [comment]
Sorry, I wasn't able to get back with this earlier.
Last state without further changes: 
[ContractId.reg.txt](https://github.com/Sycnex/Windows10Debloater/files/1418809/ContractId.reg.txt)

Until now I had always selected `no` for the privacy stuff because I wanted to keep edge as default pdf viewer for now.

After running the script one more time, even selecting the privacy stuff this time, and rebooting afterwards I got candycrush removed, however, other stuff still exists. I'll try to do a new fresh install with a single script run tomorrow.

![screen shot 2017-10-26 at 16 50 41](https://user-images.githubusercontent.com/3694534/32060268-8bf5dbae-ba6e-11e7-9b2d-cd27b9984968.png)

**Comment by Sycnex** [comment]
Okay, let me know when you run it again. Please grab the latest code.

I fixed the issue that you showed in the recent picture as well.

**Comment by Sycnex** [comment]
I wanted to check to see if you've had any time to use the latest version of the script. If so, please let me know how it worked. If not then please let me know.

**Comment by Sycnex** [comment]
I haven't gotten a response, so I am going to close this.

**Comment by Nothing4You** [comment]
We had some holidays this week, so it took me a bit to get back to this.
After a full uninstall (and reboot) executed as Administrator I'm still getting search recommendations:
![screen shot 2017-11-02 at 16 49 11](https://user-images.githubusercontent.com/3694534/32336465-b2f6870e-bfef-11e7-8132-8d16a29a5a41.png)
and advertisements.
There's also still download-pending apps and advertisements:
 ![screen shot 2017-11-02 at 16 56 51](https://user-images.githubusercontent.com/3694534/32336190-ee1dc8d4-bfee-11e7-885a-e556287f631b.png)

This is what's left in the registry:
[ContractId.reg.txt](https://github.com/Sycnex/Windows10Debloater/files/1438470/ContractId.reg.txt)

**Comment by Sycnex** [comment]
Hi Richard,

My apologies! I didn't know that.

I see that you're still getting search recommendations. In my testing it
stops it for me, but let me take a further look

I'm noticing that American users don't seem to have the same issues as
others in different countries. I'm sure there are some settings I can add
in to resolve that for you.

Let me see if I can add in something to remove those download pending a
tiles. Those tiles don't actually do anything, though. They just hang out
in the start menu.

On Nov 2, 2017 9:08 AM, "Richard Schwab" <notifications@github.com> wrote:

We had some holidays this week, so it took me a bit to get back to this.
After a full uninstall (and reboot) executed as Administrator I'm still
getting search recommendations:
[image: screen shot 2017-11-02 at 16 49 11]
<https://user-images.githubusercontent.com/3694534/32336465-b2f6870e-bfef-11e7-8132-8d16a29a5a41.png>
and advertisements.
There's also still download-pending apps and advertisements:
[image: screen shot 2017-11-02 at 16 56 51]
<https://user-images.githubusercontent.com/3694534/32336190-ee1dc8d4-bfee-11e7-885a-e556287f631b.png>

This is what's left in the registry:
ContractId.reg.txt
<https://github.com/Sycnex/Windows10Debloater/files/1438470/ContractId.reg.txt>

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Sycnex/Windows10Debloater/issues/3#issuecomment-341472305>,
or mute the thread

**Comment by Nothing4You** [comment]
In case you missed it, in the last screenshot there's also ads in the top left.
