### ISSUE TITLE
The Script removes EVERYTHING even though some apps have been removed from the script.

### ISSUE THREAD

**Issue by ghost** [Sycnex/Windows10Debloater#43]
Just got unpleasantly surprised when after editing the script to retain some apps that I need and running it, every app that I removed from the script and many more that weren't there, got removed.
My OS is now stripped of almost everything, except for things like 'OneDrive' and 'People'.

What the heck? Warhawks script used to work great, but this one 😮 

Edit: How do I get stuff like Store, Calculator, Weather, SoundRecorder etc. back?

**Comment by Sycnex** [comment]
Hi,

Sorry that has happened to you. I have not experienced that myself. Have
you tried using the revert option in the Windpws10Debloater.ps1 script?
It'll bring everything back that was removed.

And what did you modify exactly? I'm just curious so I know.

**Comment by ghost** [comment]
Here is my file:

[Windows10SysPrepDebloater.txt](https://github.com/Sycnex/Windows10Debloater/files/2321659/Windows10SysPrepDebloater.txt)

**Comment by Sycnex** [comment]
I might need to go through and take a look at the SysPrep code.

Can you try using the Windows10Debloater.ps1 and use the revert option to
get all of your stuff back? If you don't want to then here is the line of
code:

Get-AppxPackage -AllUsers | ForEach {Add-AppxPackage -Verbose
-DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

**Comment by ghost** [comment]
I've tried to use the Revert option.
From the most basic things it reinstalled only Calculator, Photos, Video Editor and Store.

I've installed SoundRecorder from the store and this time ran W10Debloater.ps1 with same modifications I've done to the other file. SoundRecorder has been uninstalled again even though it's # out in the script :(

Edit:
And OneDrive icon is present in the start menu and isn't removable, though the app is gone.

**Comment by Sycnex** [comment]
I was playing with my script and I can't say I experienced what you had experienced. I'm really sorry! Have you tried it on another test machine?

**Comment by ghost** [comment]
Unfortunately it's the only machine I'm able to use the script.
For now it's fine. I haven't ran into any issues lately and everything seems to be stable.
I have this issue always available in browser so if I'll be able to use your script again or run into any issues, I'll report back here.

**Comment by caffeinepills** [comment]
Can confirm this does indeed remove everything. It seems to ignore **both** whitelists, as it removes the store, calculator, everything. The worst part is, if it removes some provisioned packages (such as Sticky Notes) you cannot add it back. It gets removed from StoreApps library and cannot be reinstalled for all users as a provisioned package unless you reinstall Windows (or add it to an image later using dism). 

The FixWhitelistedApps function does not even run at all. I tested this to see, and even if I comment out everything else and just that function, it doesn't work. I've tested it on a Surface and a Dell, same result. (1803 Win 10) 

EDIT:  After looking into it a little more, I think the line in question is: 
Write-Verbose -Message ('Removing AppXPackages for current user')
get-appxpackage | remove-appxpackage -ErrorAction SilentlyContinue

If you run this under the local Administrator, it will remove anything and everything including the store.

**Comment by Sycnex** [comment]
I updated the script and removed Write-Verbose -Message ('Removing AppXPackages for current user')
get-appxpackage | remove-appxpackage -ErrorAction SilentlyContinue from the Begin-SysPrep function, and also removed the If statement from the FixWhitelistedApps function. 

Please let me know your experience and see if it is resolved.

**Comment by seenawardi** [comment]
Hey guys, this is URGENT. Do you guys have a solution on how to get the Store back on the images that this script has been deployed on?

I really need to fix this problem as it has caused a lot of dramas where I work.

**Comment by Sycnex** [comment]
Hi @seenawardi , choose the revert option to restore the store and all other apps.

There's a line of code in the Revert-Changes function that does this.

Here's the code:

Get-AppxPackage -AllUsers | ForEach {Add-AppxPackage -Verbose -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

Keep in mind you will need to use this code as an Administrator.

**Comment by seenawardi** [comment]
@Sycnex Hey man, We have tried that many times under admins as well but the problem still exists.

We have no store accross 30 machines and we really need to find a fix otherwise we have to reimage all and that's very very bad.

When we run the command, non of the apps come back, I think your code actually deletes all the installation files as well.

Do you have any ideas?

**Comment by Sycnex** [comment]
My code doesn't delete the actual installation files, but it removes the
appxpackages and appxprovisionedpackages from a hidden windows folder which
stores those packages. It doesn't do anything to the actual system files
themselves which is why after large anniversary updates the apps can come
back.

What version of Windows 10 are you running?

**Comment by Sycnex** [comment]
This article has some ideas but it suggests the same line of code that I
suggested as well.

Perhaps look into using DISM.

Do you have any GPOs blocking downloads of any Microsoft store apps?

https://windowsreport.com/microsoft-store-missing-after-update/

**Comment by seenawardi** [comment]
No GPO's. I have a screenshot of the error I'm getting ( https://imgur.com/a/s2MHZ9v )

Windows 10 Pro V1803

**Comment by seenawardi** [comment]
@Sycnex 

PS C:\Users\Administrator> Get-AppxPackage -AllUsers | ForEach {Add-AppxPackage -Verbose -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.Advertising.Xaml_10.1807.9.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.Advertising.Xaml_10
.1807.9.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.Advertising.Xaml_10.1807.9.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.Advertising.Xaml_10
.1807.9.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.LanguageExperiencePacken-US_17134.12.20.0_neutral__8wekyb3d8bbwe\AppXManifest.xml
".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.LanguageExperienceP
acken-US_17134.12.20.0_neutral__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.3_1.3.24201.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.3_1.3.24201.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.3_1.3.24201.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.3_1.3.24201.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.6_1.6.24903.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.6_1.6.24903.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.6_1.6.24903.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.6_1.6.24903.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.7_1.7.25531.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.7_1.7.25531.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Framework.1.7_1.7.25531.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framewor
k.1.7_1.7.25531.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Runtime.1.4_1.4.24201.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.
1.4_1.4.24201.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Runtime.1.4_1.4.24201.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.
1.4_1.4.24201.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Runtime.1.6_1.6.24903.0_x64__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.
1.6_1.6.24903.0_x64__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Program Files\WindowsApps
\Microsoft.NET.Native.Runtime.1.6_1.6.24903.0_x86__8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.
1.6_1.6.24903.0_x86__8wekyb3d8bbwe\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\Micros
oft.Windows.CloudExperienceHost_cw5n1h2txyewy\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHos
t_cw5n1h2txyewy\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\ShellE
xperienceHost_cw5n1h2txyewy\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\Ap
pXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\Micros
oft.Windows.ContentDeliveryManager_cw5n1h2txyewy\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Windows\SystemApps\Microsoft.Windows.ContentDeliveryMan
ager_cw5n1h2txyewy\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\Micros
oft.AAD.BrokerPlugin_cw5n1h2txyewy\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Windows\SystemApps\Microsoft.AAD.BrokerPlugin_cw5n1h2tx
yewy\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\ImmersiveControlP
anel\AppXManifest.xml".
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please 
contact your software vendor. (Exception from HRESULT: 0x80073CF9)
error 0x490: Unable to update the status for package 
windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy (Clear=0x0, 
Set=0x400).
NOTE: For additional information, look for [ActivityId] 
2606e7fe-5b8f-0001-1300-07268f5bd401 in the Event Log or use the command line Get-AppxLog 
-ActivityID 2606e7fe-5b8f-0001-1300-07268f5bd401
At line:1 char:38
+ ...  | ForEach {Add-AppxPackage -Verbose -DisableDevelopmentMode -Registe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Windows\Imme...ppXManifest.xml:String) [Add- 
   AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Comman 
   ds.AddAppxPackageCommand
 
VERBOSE: Operation completed for: C:\Windows\ImmersiveControlPanel\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\Micros
oft.MicrosoftEdge_8wekyb3d8bbwe\AppXManifest.xml".
VERBOSE: Operation completed for: C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbw
e\AppXManifest.xml
VERBOSE: Performing the operation "Register package" on target "C:\Windows\SystemApps\Micros
oft.Windows.Cortana_cw5n1h2txyewy\AppXManifest.xml".
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D02, The package could not be 
installed because resources it modifies are currently in use.
error 0x80073D02: Unable to install because the following apps need to be closed 
Microsoft.Windows.Cortana_1.10.7.17134_neutral_neutral_cw5n1h2txyewy.
NOTE: For additional information, look for [ActivityId] 
2606e7fe-5b8f-0003-0cfb-06268f5bd401 in the Event Log or use the command line Get-AppxLog 
-ActivityID 2606e7fe-5b8f-0003-0cfb-06268f5bd401
At line:1 char:38
+ ...  | ForEach {Add-AppxPackage -Verbose -DisableDevelopmentMode -Registe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Windows\Syst...ppXManifest.xml:String) [Ad 
   d-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Comman 
   ds.AddAppxPackageCommand
 
VERBOSE: Operation completed for: C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txy
ewy\AppXManifest.xml

**Comment by Sycnex** [comment]
So it does look like it is reinstalling apps and such as it normally
should. This still doesn't allow the store to reinstall?

**Comment by seenawardi** [comment]
No unfortunately, it doesn't seem to be installing the store at all, as in the command to install .net is there but not the store.

**Comment by Sycnex** [comment]
Try using the DISM method to resolve this.

Is this an issue on your main Image that you clone from?

**Comment by seenawardi** [comment]
@Sycnex Ya the DISM method did not resolve it neither.

Unfortunately, we have cloned the images and they are now all coming up with this issue.

Can you think of any other ideas?

**Comment by Sycnex** [comment]
Have you tried running a Windows Repair with a Windows 10 iso? Or running a
Windows refresh?

On Oct 4, 2018 3:30 AM, "seenawardi" <notifications@github.com> wrote:

@Sycnex <https://github.com/Sycnex> Ya the DISM method did not resolve it
neither.

Unfortunately, we have cloned the images and they are now all coming up
with this issue.

Can you think of any other ideas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sycnex/Windows10Debloater/issues/43#issuecomment-426967700>,
or mute the thread

**Comment by seenawardi** [comment]
Can't do that on 30 machines in 2 different cities.

**Comment by Sycnex** [comment]
I'm surprised DISM didn't work. That kind of leads me to believe that there
is something else wrong with the image you're using. Something bust me
corrupt.

**Comment by Sycnex** [comment]
I added a new blacklist function called DebloatBlacklist which will only remove the specified bloatware in the array in the function.

I also renamed the Start-Debloat function to DebloatAllApps since it seemed to remove absolutely everything related to the Microsoft Store (Any games, apps, etc).

When you hit "Yes" in the first prompt, you will be asked if you want debloat via a blacklist or if you want to remove everything, in terms of apps.

I know that this won't resolve your issue @seenawardi  but I thought you should know this. Secondly, this script now won't just remove everything, as everyone else here had experienced.

**Comment by Sycnex** [comment]
I am closing this since I haven't gotten a response. Please try the latest updates.
